name: Android CI

on:
  push:
    branches: [ master, develop, feature/* ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: build with gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
      
    - name: get failure logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: lint results
        path: app/build/reports/lint-results.html 
      
    - name: create apk
      uses: actions/upload-artifact@v1 
      if: success()
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
  
