name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: make gradlew executable
      run: chmod +x ./gradlew
      
    - name: build with gradle
      run: ./gradlew build
      
    - name: get logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: lint results
        path: app/build/reports/lint-results.html
      
    - name: create apk
      uses: actions/upload-artifact@v1 
      if: success()
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
  
