name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  DEBUG_APK_NAME: debug-apk
  DEBUG_APK_PATH: app/build/outputs/apk/debug/app-debug.apk
  LINT_RESULTS_PATH: app/build/reports/lint-results.html  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: build with gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
      
    - name: get failure logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: lint results
        path: $LINT_RESULTS_PATH
      
    - name: create apk
      uses: actions/upload-artifact@v1 
      if: success()
      with:
        name: $DEBUG_APK_NAME
        path: $DEBUG_APK_PATH
  
